# Generated by Django 2.2.1 on 2019-07-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreeName', models.CharField(max_length=50, unique=True, verbose_name='Degree Name')),
            ],
            options={
                'verbose_name_plural': 'Degree',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Course Code')),
                ('couseName', models.CharField(max_length=50, verbose_name='Course Name')),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
