# Generated by Django 2.2.1 on 2019-07-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20190702_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
